# Generated by Django 5.2.15 on 2026-06-15 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0003_add_community_and_misc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='category',
            field=models.CharField(choices=[('breeds', 'Породы'), ('care', 'Уход'), ('health', 'Здоровье'), ('nutrition', 'Питание'), ('training', 'Воспитание'), ('misc', 'Разное')], max_length=20, unique=True),
        ),
    ]
